# Generated by Django 4.2.2 on 2023-07-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_alter_document_receivers_alter_folder_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
